server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.naver.com
    port: 465
    username: mysoho2023@naver.com
    password: plehohos2023!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true


cloud:
  aws:
    credentials:
      access-key: AKIA54PFHI6SV6BS4OUS
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket:
        url: https://s3-doreen-bucket.s3.ap-northeast-2.amazonaws.com/
        name: s3-doreen-bucket
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

